### ISSUE TITLE
Something wrong with pod config

### ISSUE THREAD

**Issue by postmechanical** [comScore/ComScore-iOS-watchOS-tvOS#1] opened 2016-10-28 16:08 UTC
I get the following link errors when trying to reference `ComScore` classes from a unit test implemented in swift:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SCORAnalytics", referenced from:
      type metadata for FoobarTests.SomeDangTests.MockSCORAnalytics in SomeDangTests.o
  "_OBJC_CLASS_$_SCORClientConfiguration", referenced from:
      objc-class-ref in SomeDangTests.o
  "_OBJC_CLASS_$_SCORConfiguration", referenced from:
      type metadata for FoobarTests.SomeDangTests.MockSCORConfiguration in SomeDangTests.o
  "_OBJC_CLASS_$_SCORPublisherConfiguration", referenced from:
      objc-class-ref in SomeDangTests.o
  "_OBJC_METACLASS_$_SCORAnalytics", referenced from:
      _OBJC_METACLASS_$__TtCC13FoobarTests28SomeDangTests17MockSCORAnalytics in SomeDangTests.o
  "_OBJC_METACLASS_$_SCORConfiguration", referenced from:
      _OBJC_METACLASS_$__TtCC13FoobarTests28SomeDangTests21MockSCORConfiguration in SomeDangTests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by raspu** [comment] 2016-10-31 14:09
Are you sure you added 'ComScore' as a dependency to your unit test's target in the Podfile also? I was able to do a test of what you are describing without issues (I assumed you are targeting iOS).

**Comment by postmechanical** [comment] 2016-10-31 16:34
@raspu Targeting iOS. Tried adding the pod as a dependency of the unit test target but encounter casting issues in swift because the Obj-C classes are imported as distinct instances (e.g., `couldn't cast SCORAnalytics(<some memory address>) to SCORAnalytics(<some other memory address>)`).

**Comment by raspu** [comment] 2016-11-01 09:08
Hi @postmechanical, can you share me your Podfile, and a maybe a reduced version of your Xcode project (without any actual code) to see what the problem is?

**Comment by postmechanical** [comment] 2016-11-01 16:01
@raspu Sorry, no time to do that.

**Comment by postmechanical** [comment] 2016-11-01 18:32
```
platform :ios, "9.0"

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

project 'Foobar.xcodeproj'

target 'Foobar' do
  pod 'ComScore', '~> 5.1.7'
end

target 'FoobarTests' do
  pod 'OCMock', '~> 3.3.1'
end
```

**Comment by raspu** [comment] 2016-11-01 21:45
Assuming FoobarTests is your unit test, then you also need to add ComScore as a dependency of the unit test target:

```
platform :ios, "9.0"

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

project 'Foobar.xcodeproj'

target 'Foobar' do
  pod 'ComScore', '~> 5.1.7'
end

target 'FoobarTests' do
  pod 'OCMock', '~> 3.3.1'
  pod 'ComScore', '~> 5.1.7'
end
```

Remember to run `pod update` after changing this. 

Please refer to [CocoaPods official documentation](http://guides.cocoapods.org/using/the-podfile.html) for other alternatives and a more detailed explanation.

**Comment by postmechanical** [comment] 2016-11-01 21:59
@raspu Thanks, but that produces the second problem described. https://github.com/comScore/ComScore-iOS-watchOS-tvOS/issues/1#issuecomment-257345011

**Comment by raspu** [comment] 2016-11-01 22:03
Then I'll need an example project or steps to reproduce it, sorry but I cannot allocate time to this issue time without this first.

**Comment by postmechanical** [comment] 2016-11-01 22:05
@raspu Keep the issue open and I will try to get you a sample project within a week.

**Comment by raspu** [comment] 2016-11-01 22:07
Sure, no problem.

**Comment by raspu** [comment] 2016-11-14 13:53
I am closing this issue for now, @postmechanical if you ever find the time to create a sample project, please re-open it.

**Closed by raspu** 2016-11-14 13:53 UTC
